services:
  # OmniSuite API
  omnisuite-api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: omnisuite-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "OmniSuite.API.dll"]
    restart: unless-stopped
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: omnisuite_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Senha@123
      MYSQL_DATABASE: omnisuite
      MYSQL_USER: omnisuite
      MYSQL_PASSWORD: Senha@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
